/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.68).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.example.lab2.controlers.rest;

import com.example.lab2.models.dto.FamilyDTO;
import com.example.lab2.models.dto.MoneyDTO;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import javax.validation.Valid;
import java.util.List;

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2025-04-29T17:08:35.048350733Z[GMT]")
@Validated
public interface FamilyApi {

    @Operation(summary = "Баланс семьи", description = "Возвращает сумму баланса по id семьи", tags={ "Family" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "Успешное выполнение", content = @Content(mediaType = "application/json", schema = @Schema(implementation = Double.class))),
        
        @ApiResponse(responseCode = "401", description = "Требуется аутентификация"),
        
        @ApiResponse(responseCode = "403", description = "Доступ запрещен"),
        
        @ApiResponse(responseCode = "404", description = "Семья не найдена") })
    @RequestMapping(value = "/family/balance/{familyId}",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<Double> familyBalanceFamilyIdGet(@Parameter(in = ParameterIn.PATH, description = "ID семьи", required=true, schema=@Schema()) @PathVariable("familyId") Integer familyId
);


    @Operation(summary = "Пополнить баланс семьи", description = "Пополняет баланс семьи по id", tags={ "Family" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "201", description = "Баланс успешно пополнен"),
        
        @ApiResponse(responseCode = "401", description = "Требуется аутентификация"),
        
        @ApiResponse(responseCode = "403", description = "Доступ запрещен"),
        
        @ApiResponse(responseCode = "404", description = "Семья не найдена") })
    @RequestMapping(value = "/family/balance/{familyId}",
        consumes = { "application/json" }, 
        method = RequestMethod.POST)
    ResponseEntity<Void> familyBalanceFamilyIdPost(@Parameter(in = ParameterIn.PATH, description = "ID семьи", required=true, schema=@Schema()) @PathVariable("familyId") Integer familyId
, @Parameter(in = ParameterIn.DEFAULT, description = "", required=true, schema=@Schema()) @Valid @RequestBody MoneyDTO body
);



}

