/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.68).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.example.lab2.controlers.rest;

import com.example.lab2.model.dto.UserDTO;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import javax.validation.Valid;
import java.util.List;

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2025-04-29T17:08:35.048350733Z[GMT]")
@Validated
public interface UsersApi {

    @Operation(summary = "Добавить пользователя в семью", description = "Добавляет нового пользователя в семью", tags={ "Users" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "201", description = "Пользователь успешно добавлен"),
        
        @ApiResponse(responseCode = "401", description = "Требуется аутентификация"),
        
        @ApiResponse(responseCode = "403", description = "Доступ запрещен"),
        
        @ApiResponse(responseCode = "404", description = "Семья не найдена") })
    @RequestMapping(value = "/users/{familyId}",
        consumes = { "application/json" }, 
        method = RequestMethod.POST)
    ResponseEntity<Void> usersFamilyIdPost(@Parameter(in = ParameterIn.PATH, description = "ID семьи", required=true, schema=@Schema()) @PathVariable("familyId") Integer familyId
, @Parameter(in = ParameterIn.DEFAULT, description = "", required=true, schema=@Schema()) @Valid @RequestBody UserDTO body
);




    @Operation(summary = "Удалить пользователя", description = "Удаление пользователя по id", tags={ "Users" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "204", description = "Пользователь успешно удален"),
        
        @ApiResponse(responseCode = "401", description = "Требуется аутентификация"),
        
        @ApiResponse(responseCode = "403", description = "Доступ запрещен"),
        
        @ApiResponse(responseCode = "404", description = "Пользователь не найден") })
    @RequestMapping(value = "/users/{userId}",
        method = RequestMethod.DELETE)
    ResponseEntity<Void> usersUserIdDelete(@Parameter(in = ParameterIn.PATH, description = "ID пользователя", required=true, schema=@Schema()) @PathVariable("userId") Integer userId
);


    @Operation(summary = "Получить пользователя", description = "Получение пользователя по id", tags={ "Users" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "Успешное выполнение", content = @Content(mediaType = "application/json", schema = @Schema(implementation = UserDTO.class))),
        
        @ApiResponse(responseCode = "401", description = "Требуется аутентификация"),
        
        @ApiResponse(responseCode = "403", description = "Доступ запрещен"),
        
        @ApiResponse(responseCode = "404", description = "Пользователь не найден"),

        @ApiResponse(responseCode = "500", description = "Ошибка обработки") })
    @RequestMapping(value = "/users/{userId}",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<UserDTO> usersUserIdGet(@Parameter(in = ParameterIn.PATH, description = "ID пользователя", required=true, schema=@Schema()) @PathVariable("userId") Integer userId
);

    @Operation(summary = "Получить список пользователей", description = "Получение списка пользователей", tags={ "Users" })
    @ApiResponses(value = {
            @ApiResponse(responseCode = "200", description = "Успешное выполнение", content = @Content(mediaType = "application/json",array = @ArraySchema(schema = @Schema(implementation = UserDTO.class)))),

            @ApiResponse(responseCode = "401", description = "Требуется аутентификация"),

            @ApiResponse(responseCode = "403", description = "Доступ запрещен"),

            @ApiResponse(responseCode = "404", description = "Пользователь не найден"),

            @ApiResponse(responseCode = "500", description = "Ошибка обработки") })
    @RequestMapping(value = "/users",
            produces = { "application/json" },
            method = RequestMethod.GET)
    ResponseEntity<List<UserDTO>> usersGet();


}

